version: '3.9'

services:
  front-end:
    build: ./back-end
    ports:
      - 9000
    depends_on:
      - back-end

  back-end:
    build: ./front-end
    ports:
      - 5252

  proxy:
    build: ./proxy 
    ports:
      - 80:80
    depends_on:
      - front-end
      - back-end

#docker-compose build
#docker-compose up