services:
  front-end:
    build:
      context: ./front-end
    ports:
      - 9000:9000
    depends_on:
      - back-end

  back-end:
    build:
      context: ./back-end
    ports:
      - 5252:5252

  proxy:
    build:
      context: ./proxy 
    ports:
      - 80:80
    depends_on:
      - front-end
      - back-end

#docker-compose build
#docker-compose up
